* My Dotfiles

This is my dotfiles repository managed with GNU Stow.

** Installation
Clone the current project to the home directory.

To install the dotfiles (create symlinks to your home directory):

#+begin_src sh
make
#+end_src

Or explicitly:

#+begin_src sh
make stow
#+end_src

This runs =stow .= which creates symbolic links from your home directory to the files in this repository.

** Cleaning Up

To remove all symlinks created by stow:

#+begin_src sh
make clean
#+end_src

This runs =stow -D .= which deletes the symbolic links.

** Prerequisites

Make sure you have GNU Stow installed:

- macOS: =brew install stow=
- Ubuntu/Debian: =sudo apt install stow=
- Arch Linux: =sudo pacman -S stow=

*** macos
#+begin_src bash
brew install zsh eza fzf antidote yazi carapace zoxide direnv
#+end_src
*** arch
#+begin_src bash
yay -S zsh eza fzf antidote yazi carapace-bin zoxide direnv
#+end_src
*** ubuntu
#+begin_src bash
sudo apt install zsh eza fzf  zoxide direnv
#+end_src

antidote 自动使用 git 安装。

**** carapace-bin
#+begin_src bash
  echo "deb [trusted=yes] https://apt.fury.io/rsteube/ /" | sudo tee /etc/apt/sources.list.d/fury.list && sudo apt-get update && sudo apt-get install -y carapace-bin
#+end_src
** oh-my-zsh
[[https://ohmyz.sh/][Oh My Zsh - a delightful & open source framework for Zsh]]
*** install
#+begin_src bash
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#+end_src
*** plugins
- zsh-autosuggestions
  #+begin_src bash
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  #+end_src
- powerlevel10k
  #+begin_src bash
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  #+end_src
- zsh-syntax-highlighting
  #+begin_src bash
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  #+end_src
