* My Dotfiles

This is my dotfiles repository managed with GNU Stow.

** Installation
Clone the current project to the home directory.

To install the dotfiles (create symlinks to your home directory):

#+begin_src sh
make
#+end_src

Or explicitly:

#+begin_src sh
make stow
#+end_src

This runs =stow .= which creates symbolic links from your home directory to the files in this repository.

** Cleaning Up

To remove all symlinks created by stow:

#+begin_src sh
make clean
#+end_src

This runs =stow -D .= which deletes the symbolic links.

** Prerequisites

Make sure you have GNU Stow installed:

- macOS: =brew install stow=
- Ubuntu/Debian: =sudo apt install stow=
- Arch Linux: =sudo pacman -S stow=

*** macos
#+begin_src bash
brew install zsh eza fzf antidote yazi carapace zoxide direnv
#+end_src
*** arch
#+begin_src bash
yay -S zsh eza fzf antidote yazi carapace-bin zoxide direnv
#+end_src
*** ubuntu
#+begin_src bash
sudo apt install zsh eza fzf  zoxide direnv
#+end_src

antidote 自动使用 git 安装。

**** carapace-bin
#+begin_src bash
  echo "deb [trusted=yes] https://apt.fury.io/rsteube/ /" | sudo tee /etc/apt/sources.list.d/fury.list && sudo apt-get update && sudo apt-get install -y carapace-bin
#+end_src
*** chang default shell
#+begin_src bash
  chsh -s $(which zsh)
  chsh -s $(which bash)
#+end_src
** antidote
[[https://getantidote.github.io/][antidote]] 是 zsh 插件管理器。安装系统包（见上方 Prerequisites）或首次开 shell 时会 clone 到 =~/.antidote= 。
*** antidote 会按 =~/.zsh_plugins.txt= （本仓库 =dot-zsh_plugins.txt= ）用 git 自动克隆插件。
*** 用法
- 插件清单： =~/.zsh_plugins.txt=
- 更新插件： =antidote update=
- 查看已装： =antidote list=
